# Generated by Django 5.1.15 on 2026-04-30 14:20

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AppMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                (
                    "meta_type",
                    models.CharField(
                        choices=[
                            ("announcement", "Announcement Popup"),
                            ("update_warning", "Force Update Warning"),
                            ("maintenance", "Maintenance Notice"),
                            ("promotional", "Promotional Banner"),
                            ("home_banner", "Home Screen Banner"),
                        ],
                        max_length=15,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("cta_label", models.CharField(blank=True, max_length=50)),
                ("cta_url", models.URLField(blank=True, max_length=500)),
                (
                    "target_platform",
                    models.CharField(
                        choices=[
                            ("all", "All Platforms"),
                            ("android", "Android"),
                            ("ios", "iOS"),
                            ("web", "Web"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("min_app_version", models.CharField(blank=True, max_length=20)),
                ("max_app_version", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("is_dismissible", models.BooleanField(default=True)),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("extra_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="app_metadata",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "app_meta_data",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BizListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField()),
                (
                    "opportunity_type",
                    models.CharField(
                        choices=[
                            ("franchise", "Franchise"),
                            ("investment", "Investment"),
                            ("channel_partner", "Channel Partner"),
                            ("joint_venture", "Joint Venture"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("venue", models.CharField(blank=True, max_length=200)),
                (
                    "investment_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "investment_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("investment_display", models.CharField(blank=True, max_length=100)),
                ("date_info", models.CharField(blank=True, max_length=100)),
                ("closing_date", models.DateField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=100)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("image_2_url", models.URLField(blank=True, max_length=500)),
                ("image_3_url", models.URLField(blank=True, max_length=500)),
                ("image_4_url", models.URLField(blank=True, max_length=500)),
                ("image_5_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_expired", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("upvotes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("saves_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_biz_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="biz_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "biz_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FiltersMetaData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filter_context",
                    models.CharField(
                        choices=[("job", "Job Listings"), ("biz", "Biz Listings")],
                        max_length=5,
                    ),
                ),
                ("selected_categories", models.JSONField(blank=True, default=list)),
                ("selected_locations", models.JSONField(blank=True, default=list)),
                (
                    "selected_experience_levels",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "selected_opportunity_types",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "sort_preference",
                    models.CharField(
                        choices=[
                            ("most_recent", "Most Recent"),
                            ("most_upvoted", "Most Upvoted"),
                            ("salary_high", "Salary High to Low"),
                            ("investment_low", "Investment Low to High"),
                        ],
                        default="most_recent",
                        max_length=15,
                    ),
                ),
                ("search_query", models.CharField(blank=True, max_length=255)),
                ("remote_only", models.BooleanField(default=False)),
                ("verified_only", models.BooleanField(default=False)),
                ("hide_expired", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "filters_meta_data",
            },
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("sub_category", models.CharField(blank=True, max_length=100)),
                ("qualification", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=200)),
                (
                    "experience_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fresher", "Fresher"),
                            ("1-3_yrs", "1–3 Years"),
                            ("3-5_yrs", "3–5 Years"),
                            ("5+_yrs", "5+ Years"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "salary_min",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "salary_max",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("salary_display", models.CharField(blank=True, max_length=100)),
                ("application_deadline", models.DateField(blank=True, null=True)),
                ("source_name", models.CharField(blank=True, max_length=100)),
                ("source_url", models.URLField(blank=True, max_length=500)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("is_trending", models.BooleanField(default=False)),
                ("is_new", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_verified", models.BooleanField(default=False)),
                ("thumbnail_url", models.URLField(blank=True, max_length=500)),
                ("image_2_url", models.URLField(blank=True, max_length=500)),
                ("image_3_url", models.URLField(blank=True, max_length=500)),
                ("image_4_url", models.URLField(blank=True, max_length=500)),
                ("image_5_url", models.URLField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("is_expired", models.BooleanField(default=False)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("upvotes_count", models.PositiveIntegerField(default=0)),
                ("comments_count", models.PositiveIntegerField(default=0)),
                ("saves_count", models.PositiveIntegerField(default=0)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_job_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="job_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "job_listings",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FileManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_url", models.URLField(max_length=500)),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word Document"),
                            ("xlsx", "Excel"),
                            ("csv", "CSV"),
                            ("ppt", "PowerPoint"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=10,
                    ),
                ),
                ("mime_type", models.CharField(blank=True, max_length=100)),
                (
                    "file_size_bytes",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.bizlisting",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="core.joblisting",
                    ),
                ),
            ],
            options={
                "db_table": "file_management",
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("job", "Job"), ("biz", "Business")], max_length=5
                    ),
                ),
                ("text", models.TextField(max_length=2000)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.bizlisting",
                    ),
                ),
                (
                    "parent_comment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="core.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="core.joblisting",
                    ),
                ),
            ],
            options={
                "db_table": "comments",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("job", "Job"), ("biz", "Business")], max_length=5
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("incorrect_info", "Incorrect information"),
                            ("duplicate", "Duplicate listing"),
                            ("spam", "Spam or misleading"),
                            ("expired", "Expired / outdated"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("reviewed", "Reviewed"),
                            ("resolved", "Resolved — action taken"),
                            ("dismissed", "Dismissed — no action"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.bizlisting",
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports",
                        to="core.joblisting",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "listing_reports",
            },
        ),
        migrations.CreateModel(
            name="PointsHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("earned", "Earned"),
                            ("redeemed", "Redeemed"),
                            ("expired", "Expired"),
                            ("adjusted", "Admin Adjusted"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("listing_approved", "Listing Approved"),
                            ("referral", "Referral"),
                            ("profile_complete", "Profile Completed"),
                            ("daily_login", "Daily Login"),
                            ("comment_posted", "Comment Posted"),
                            ("bonus", "Bonus"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("points", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bizlisting",
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="points_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "points_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SavedAndAppliedListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("job", "Job"), ("biz", "Business")], max_length=5
                    ),
                ),
                ("is_saved", models.BooleanField(default=False)),
                ("is_applied", models.BooleanField(default=False)),
                ("saved_at", models.DateTimeField(blank=True, null=True)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="core.bizlisting",
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by_users",
                        to="core.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_applied",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "saved_and_applied_listings",
            },
        ),
        migrations.CreateModel(
            name="SubscriptionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("premium_monthly", "Premium Monthly"),
                            ("premium_yearly", "Premium Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("plan_display_name", models.CharField(blank=True, max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="INR", max_length=5)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("initiated", "Initiated"),
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="initiated",
                        max_length=10,
                    ),
                ),
                ("payment_gateway", models.CharField(blank=True, max_length=50)),
                ("gateway_order_id", models.CharField(blank=True, max_length=255)),
                ("gateway_payment_id", models.CharField(blank=True, max_length=255)),
                ("gateway_signature", models.CharField(blank=True, max_length=500)),
                ("subscription_start", models.DateTimeField(blank=True, null=True)),
                ("subscription_end", models.DateTimeField(blank=True, null=True)),
                ("is_auto_renew", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscriptions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "subscription_history",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Upvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("job", "Job"), ("biz", "Business")], max_length=5
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="core.bizlisting",
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to="core.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "upvotes",
            },
        ),
        migrations.CreateModel(
            name="UserActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("signup", "Sign Up"),
                            ("view_listing", "View Listing"),
                            ("save_listing", "Save Listing"),
                            ("unsave_listing", "Unsave Listing"),
                            ("upvote", "Upvote"),
                            ("unvote", "Remove Upvote"),
                            ("mark_applied", "Mark as Applied"),
                            ("post_comment", "Post Comment"),
                            ("report_listing", "Report Listing"),
                            ("submit_listing", "Submit Listing"),
                            ("profile_update", "Profile Update"),
                            ("filter_change", "Filter Changed"),
                            ("search", "Search"),
                            ("share_listing", "Share Listing"),
                            ("upgrade_premium", "Upgrade to Premium"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        blank=True,
                        choices=[("job", "Job"), ("biz", "Business")],
                        max_length=5,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("device_type", models.CharField(blank=True, max_length=15)),
                ("app_version", models.CharField(blank=True, max_length=20)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "biz_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.bizlisting",
                    ),
                ),
                (
                    "job_listing",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.joblisting",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_activity_log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        max_length=20,
                    ),
                ),
                ("state", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("profile_picture_url", models.URLField(blank=True, max_length=500)),
                ("job_preferences", models.JSONField(blank=True, default=list)),
                ("is_premium", models.BooleanField(default=False)),
                ("premium_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("deletion_requested", "Deletion Requested"),
                            ("deactivated", "Deactivated"),
                        ],
                        default="active",
                        max_length=25,
                    ),
                ),
                ("deletion_requested_at", models.DateTimeField(blank=True, null=True)),
                ("total_points", models.PositiveIntegerField(default=0)),
                (
                    "points_level",
                    models.CharField(
                        choices=[
                            ("newcomer", "Newcomer"),
                            ("contributor", "Contributor"),
                            ("champion", "Champion"),
                            ("legend", "Legend"),
                        ],
                        default="newcomer",
                        max_length=15,
                    ),
                ),
                ("total_posts", models.PositiveIntegerField(default=0)),
                ("total_saved", models.PositiveIntegerField(default=0)),
                ("total_upvotes_given", models.PositiveIntegerField(default=0)),
                ("otp_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_details",
            },
        ),
        migrations.AddIndex(
            model_name="bizlisting",
            index=models.Index(
                fields=["status", "is_expired"], name="biz_listing_status_37aacc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bizlisting",
            index=models.Index(
                fields=["category"], name="biz_listing_categor_a39c09_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bizlisting",
            index=models.Index(
                fields=["opportunity_type"], name="biz_listing_opportu_0e5685_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bizlisting",
            index=models.Index(
                fields=["upvotes_count"], name="biz_listing_upvotes_171f6d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bizlisting",
            index=models.Index(
                fields=["created_at"], name="biz_listing_created_cec07e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="filtersmetadata",
            unique_together={("user", "filter_context")},
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["status", "is_expired"], name="job_listing_status_cb619f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["category"], name="job_listing_categor_6a74a6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["location"], name="job_listing_locatio_b02fbb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["upvotes_count"], name="job_listing_upvotes_1b14d5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="joblisting",
            index=models.Index(
                fields=["created_at"], name="job_listing_created_6a05ab_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["job_listing", "is_deleted"], name="comments_job_lis_ae3ee4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["biz_listing", "is_deleted"], name="comments_biz_lis_3fe60e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["parent_comment"], name="comments_parent__4366da_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingreport",
            index=models.Index(fields=["status"], name="listing_rep_status_e85402_idx"),
        ),
        migrations.AddIndex(
            model_name="listingreport",
            index=models.Index(
                fields=["job_listing", "status"], name="listing_rep_job_lis_e7357f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listingreport",
            index=models.Index(
                fields=["biz_listing", "status"], name="listing_rep_biz_lis_5d0826_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_listing__isnull", False)),
                fields=("user", "job_listing"),
                name="unique_report_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="listingreport",
            constraint=models.UniqueConstraint(
                condition=models.Q(("biz_listing__isnull", False)),
                fields=("user", "biz_listing"),
                name="unique_report_biz",
            ),
        ),
        migrations.AddIndex(
            model_name="pointshistory",
            index=models.Index(
                fields=["user", "created_at"], name="points_hist_user_id_2bf76f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedandappliedlisting",
            index=models.Index(
                fields=["user", "is_saved"], name="saved_and_a_user_id_ac4666_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="savedandappliedlisting",
            index=models.Index(
                fields=["user", "is_applied"], name="saved_and_a_user_id_897736_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="savedandappliedlisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_listing__isnull", False)),
                fields=("user", "job_listing"),
                name="unique_user_job_listing",
            ),
        ),
        migrations.AddConstraint(
            model_name="savedandappliedlisting",
            constraint=models.UniqueConstraint(
                condition=models.Q(("biz_listing__isnull", False)),
                fields=("user", "biz_listing"),
                name="unique_user_biz_listing",
            ),
        ),
        migrations.AddIndex(
            model_name="upvote",
            index=models.Index(
                fields=["job_listing"], name="upvotes_job_lis_03fdda_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="upvote",
            index=models.Index(
                fields=["biz_listing"], name="upvotes_biz_lis_bc6e76_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="upvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("job_listing__isnull", False)),
                fields=("user", "job_listing"),
                name="unique_upvote_job",
            ),
        ),
        migrations.AddConstraint(
            model_name="upvote",
            constraint=models.UniqueConstraint(
                condition=models.Q(("biz_listing__isnull", False)),
                fields=("user", "biz_listing"),
                name="unique_upvote_biz",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["user", "action_type"], name="user_activi_user_id_23d7f4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["action_type", "created_at"],
                name="user_activi_action__23eb70_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="useractivitylog",
            index=models.Index(
                fields=["created_at"], name="user_activi_created_0025ca_idx"
            ),
        ),
    ]
